// Code generated by iconcatalog. DO NOT EDIT.
// Source catalog SHA-256: d83be964fa411e87c61b49f0a0b6a2a1465f33ad43bea7cd93b2e434b59266af
// Source catalog schema: v1

package brandicons

import "github.com/araihu/goshtoso/components/icon"

type Glyph struct {
	GoName        string
	CanonicalName string
	Symbol        icon.Symbol
}

const SpriteURL = "/assets/araihu/v0.1.0/icons/brand/sprite.svg"

const (
	IconAraihuIconDarkPlateOptical             icon.Symbol = "araihu-icon-dark-plate-optical"
	IconAraihuIconDarkTransparentOptical       icon.Symbol = "araihu-icon-dark-transparent-optical"
	IconAraihuIconGrayscalePlateOptical        icon.Symbol = "araihu-icon-grayscale-plate-optical"
	IconAraihuIconGrayscaleTransparentOptical  icon.Symbol = "araihu-icon-grayscale-transparent-optical"
	IconAraihuIconLightPlateOptical            icon.Symbol = "araihu-icon-light-plate-optical"
	IconAraihuIconLightTransparentOptical      icon.Symbol = "araihu-icon-light-transparent-optical"
	IconAraihuIconMonochromeTransparentOptical icon.Symbol = "araihu-icon-monochrome-transparent-optical"
	IconAraihuIconTintedPlateLauncher          icon.Symbol = "araihu-icon-tinted-plate-launcher"
	IconAraihuIconTintedPlateOptical           icon.Symbol = "araihu-icon-tinted-plate-optical"
	IconAraihuIconTintedTransparentOptical     icon.Symbol = "araihu-icon-tinted-transparent-optical"
	IconAraihuLogoDarkPlateOptical             icon.Symbol = "araihu-logo-dark-plate-optical"
	IconAraihuLogoDarkTransparentOptical       icon.Symbol = "araihu-logo-dark-transparent-optical"
	IconAraihuLogoGrayscalePlateOptical        icon.Symbol = "araihu-logo-grayscale-plate-optical"
	IconAraihuLogoGrayscaleTransparentOptical  icon.Symbol = "araihu-logo-grayscale-transparent-optical"
	IconAraihuLogoLightPlateOptical            icon.Symbol = "araihu-logo-light-plate-optical"
	IconAraihuLogoLightTransparentOptical      icon.Symbol = "araihu-logo-light-transparent-optical"
	IconAraihuLogoMonochromeTransparentOptical icon.Symbol = "araihu-logo-monochrome-transparent-optical"
	IconAraihuLogoTintedPlateOptical           icon.Symbol = "araihu-logo-tinted-plate-optical"
	IconAraihuLogoTintedTransparentOptical     icon.Symbol = "araihu-logo-tinted-transparent-optical"
)

var Glyphs = []Glyph{
	{
		GoName:        "IconAraihuIconDarkPlateOptical",
		CanonicalName: "araihu-icon-dark-plate-optical",
		Symbol:        IconAraihuIconDarkPlateOptical,
	},
	{
		GoName:        "IconAraihuIconDarkTransparentOptical",
		CanonicalName: "araihu-icon-dark-transparent-optical",
		Symbol:        IconAraihuIconDarkTransparentOptical,
	},
	{
		GoName:        "IconAraihuIconGrayscalePlateOptical",
		CanonicalName: "araihu-icon-grayscale-plate-optical",
		Symbol:        IconAraihuIconGrayscalePlateOptical,
	},
	{
		GoName:        "IconAraihuIconGrayscaleTransparentOptical",
		CanonicalName: "araihu-icon-grayscale-transparent-optical",
		Symbol:        IconAraihuIconGrayscaleTransparentOptical,
	},
	{
		GoName:        "IconAraihuIconLightPlateOptical",
		CanonicalName: "araihu-icon-light-plate-optical",
		Symbol:        IconAraihuIconLightPlateOptical,
	},
	{
		GoName:        "IconAraihuIconLightTransparentOptical",
		CanonicalName: "araihu-icon-light-transparent-optical",
		Symbol:        IconAraihuIconLightTransparentOptical,
	},
	{
		GoName:        "IconAraihuIconMonochromeTransparentOptical",
		CanonicalName: "araihu-icon-monochrome-transparent-optical",
		Symbol:        IconAraihuIconMonochromeTransparentOptical,
	},
	{
		GoName:        "IconAraihuIconTintedPlateLauncher",
		CanonicalName: "araihu-icon-tinted-plate-launcher",
		Symbol:        IconAraihuIconTintedPlateLauncher,
	},
	{
		GoName:        "IconAraihuIconTintedPlateOptical",
		CanonicalName: "araihu-icon-tinted-plate-optical",
		Symbol:        IconAraihuIconTintedPlateOptical,
	},
	{
		GoName:        "IconAraihuIconTintedTransparentOptical",
		CanonicalName: "araihu-icon-tinted-transparent-optical",
		Symbol:        IconAraihuIconTintedTransparentOptical,
	},
	{
		GoName:        "IconAraihuLogoDarkPlateOptical",
		CanonicalName: "araihu-logo-dark-plate-optical",
		Symbol:        IconAraihuLogoDarkPlateOptical,
	},
	{
		GoName:        "IconAraihuLogoDarkTransparentOptical",
		CanonicalName: "araihu-logo-dark-transparent-optical",
		Symbol:        IconAraihuLogoDarkTransparentOptical,
	},
	{
		GoName:        "IconAraihuLogoGrayscalePlateOptical",
		CanonicalName: "araihu-logo-grayscale-plate-optical",
		Symbol:        IconAraihuLogoGrayscalePlateOptical,
	},
	{
		GoName:        "IconAraihuLogoGrayscaleTransparentOptical",
		CanonicalName: "araihu-logo-grayscale-transparent-optical",
		Symbol:        IconAraihuLogoGrayscaleTransparentOptical,
	},
	{
		GoName:        "IconAraihuLogoLightPlateOptical",
		CanonicalName: "araihu-logo-light-plate-optical",
		Symbol:        IconAraihuLogoLightPlateOptical,
	},
	{
		GoName:        "IconAraihuLogoLightTransparentOptical",
		CanonicalName: "araihu-logo-light-transparent-optical",
		Symbol:        IconAraihuLogoLightTransparentOptical,
	},
	{
		GoName:        "IconAraihuLogoMonochromeTransparentOptical",
		CanonicalName: "araihu-logo-monochrome-transparent-optical",
		Symbol:        IconAraihuLogoMonochromeTransparentOptical,
	},
	{
		GoName:        "IconAraihuLogoTintedPlateOptical",
		CanonicalName: "araihu-logo-tinted-plate-optical",
		Symbol:        IconAraihuLogoTintedPlateOptical,
	},
	{
		GoName:        "IconAraihuLogoTintedTransparentOptical",
		CanonicalName: "araihu-logo-tinted-transparent-optical",
		Symbol:        IconAraihuLogoTintedTransparentOptical,
	},
}
